### ISSUE TITLE
Push object strings into hooks

### ISSUE THREAD

**Issue by amorskoy** [tidwall/tile38#93] opened 2016-12-08 15:22 UTC
Suppose example from tutorial:

SET people bob POINT 33.01 -115.01
SET people alice POINT 33.02 -115.02
SET people alice:lastname STRING "Denton"
SETHOOK myhook http://10.0.1.5/hook NEARBY people FENCE ROAM people * 5000

Currently hook's POST data does not contain alice:lastname. Is it possible to have?

**Comment by tidwall** [comment] 2016-12-08 17:00
Hi @amorskoy,

This is not currently possible. A roaming geofence only passes the id, key, and distance of the nearby matches. This is by design to keep the notification as lightweight as possible.

Then you would need to issue a SCAN command for `alice:*`. Let's say you get the  notification:
```json
{"command":"set","detect":"roam","hook":"",
"time":"2016-12-08T09:27:54.306035387-07:00",
"key":"people","id":"bob",
"object":{"type":"Point","coordinates":[-115.01,33.01]},
"nearby":{"key":"people","id":"alice","meters":1451.138152186708}}
```
and then you can send:
```
SCAN people MATCH alice:*
```
to retrieve the all child strings of alice. 

Would this work for your use-case? If not, perhaps a new keyword specifically for roaming result such as:

```
SETHOOK myhook http://10.0.1.5/hook NEARBY people FENCE ROAM people * 5000 DETAILS :*
```

This then this would do a SCAN under the hood and return with the notification.

**Comment by amorskoy** [comment] 2016-12-09 08:03
Thanks @tidwall .
I believe, that SCAN at the end of SETHOOK (when it is implemented) would be great thing.
I agree with you about traffic overhead - but in fact, without such feature I should keep shadow copy of objects in <key, value_object> store (like memcached or more comple noSQL solution) - wich complicates architectural things.
So voting for SETHOOK ..... FENCE ROAM .... SCAN :)

**Comment by tidwall** [comment] 2016-12-09 17:16
Sounds good. I think this is doable. I'm moving this to #96 now.

**Closed by tidwall** 2016-12-09 17:16 UTC
