### ISSUE TITLE
Tile38 slow, then crashes fatally

### ISSUE THREAD

**Issue by damariei** [tidwall/tile38#173] opened 2017-04-24 10:58 UTC
Hello,

We had a major bug with tile38 yesterday. At first, we noticed all our requests were timing out, then tile38 server completely crashed.

For information, we had a few (less than 100) geo polygons set. Plus, around ~1500 geofences with webhooks, and around ~1.5million points (in a separate collection, with new points being created at a rate of about, 1.5k/minute). 

I have attached the the full crash log with errors here:
https://gist.github.com/damariei/5104167b40c3ebbd50441cb576398a3b

Let me know what other information I can provide to help debug this.

**Comment by m1ome** [comment] 2017-04-24 11:26
@damariei seems like a race bug

**Comment by damariei** [comment] 2017-04-24 11:30
For more information, our geofences currently use HTTP. I imagine since tile38 waits for a 200 response, if the webhook endpoint is having problems, this could really backlog tile38 as well.

**Comment by m1ome** [comment] 2017-04-24 11:37
Can you test up with a 1.9.0? 
It have a rewritten HTTP webhook support.

**Comment by m1ome** [comment] 2017-04-24 11:41
All this system of background expiration was refactored in 1.9.0
You should definitely try and check if 1.9.0 also have this bug.

**Comment by damariei** [comment] 2017-04-24 11:43
Correct me if I am wrong, but according to the release notes, I only see changes to webhooks done in 1.8.0 (which we are running). For example:
`#147: Leaking http hook connections (@mkabischev)`

I see nothing about webhooks in 1.9.0

**Comment by damariei** [comment] 2017-04-24 11:43
If by background expiration, you mean TTLs, note that we are currently not using them.

**Comment by tidwall** [comment] 2017-04-24 14:14
@damariei Thanks for providing the crashlog

This appears to be an issue in 1.8.0 and it should be fixed in 1.9.0.

The exact issue is because the `backgroundExpires` func uses a method that swaps the read and write locks depending on the operation, and https://github.com/tidwall/tile38/blob/1.8.0/controller/expire.go#L89 is missing the swap.

```go
if !del {
    return nodelay
}
```

Should be:

```go
if !del {
    c.mu.Unlock()
    c.mu.RLock()
    return nodelay
}
```

@damariei Could you see if upgrading to 1.9.0 helps?

**Comment by m1ome** [comment] 2017-04-24 15:17
@tidwall yep, that's why i asked to migrate to 1.9.0, because `backgroundExpires` looks totally reworked.

**Comment by damariei** [comment] 2017-04-24 17:02
Okay, at the moment, I am trying to reproduce the error under load testing. If you guys have any ideas, that would be great.

**Comment by tidwall** [comment] 2017-04-24 18:24
The error is rare, but it can happen when an object is marked for expiration and then unmarked.

To be exact, the backgroundExpires routine looks for objects that are marked for expiration within a read-locked mutex. If it finds one it will then swap the lock with a write lock and double check if the object still needs to be deleted. (the double check is because there's a slim chance that the object that was previously marked is no longer needing deletion). If the object is still marked then the routine deletes it from the database, otherwise the object is ignored and lock is swapped back to a read-lock. This last part is the bug, because the swap does not happen.

It's probably less than a microsecond between the lock swaps, so it may be really hard to reproduce in the wild.

I haven't tried, but my initial idea is to SET a lot of objects with the EX option mixed with a lot of SETs with no EX. I would make a list of like 100 points with predefined keys and ids. 

```go
var points []point // ... fill this with random point data with unique: lat, lon, and id
start := time.Now()
for {
    point := rand.Int()%len(points) // get a random point
    if rand.Int()%2 == 0 {
        exec("SET", point.key, point.id, "EX", 10, "POINT", point.lat, point.lon)
    } else {
        exec("SET", point.key, point.id, "POINT", point.lat, point.lon)
    }
    if time.Since(start) > time.Minute{
        break // run for one minute
    }
}
```

**Comment by m1ome** [comment] 2017-04-24 20:13
@tidwall we need to use -race on test suites.

**Comment by tidwall** [comment] 2017-04-24 20:18
@m1ome I agree, but would -race detect this issue?  AFAIK -race only detect if two goroutines are accessing the same memory at the same time, which isn't the problem in this case.

**Comment by m1ome** [comment] 2017-04-25 04:56
@tidwall hmmm, yes you are right. Need to check this one.

**Comment by tidwall** [comment] 2018-04-24 01:46
I’m closing this issue because it has been inactive for a few months. Please reopen if needed. 

Thank you!

**Closed by tidwall** 2018-04-24 01:46 UTC
