### ISSUE TITLE
geojson: Implement json.Unmarshaler and/or use `json` tagged fields

### ISSUE THREAD

**Issue by Volox** [tidwall/tile38#31] opened 2016-08-10 15:10 UTC
Mostly due to #18 it would be great to implement both golang json interfaces (`json.Unmarshaler` and `json.Marshaler`) so a GeoJSON can be loaded directly from a file.

Also checking the code i noticed that most the work (the actual byte parsing) is already done.

**Comment by tidwall** [comment] 2016-08-11 10:06
Thanks for the suggestion. I'd be happy to add this feature, but I'm not sure of the best approach to making it work. 

If it's not too much trouble, Could you provide an example of how you would use it in code?

**Comment by umpc** [comment] 2016-10-14 03:04
I really wanted this functionality for saving time. If someone is interested in this, my local fork has the methods: https://github.com/umpc/tile38/commit/5b0620e68e731099fdedae79cb88c238c97764a8

If someone who uses fields/values would like to properly test them, perhaps it could be merged into Tile38. I have a hunch that this current implementation of the methods does not work properly for fields/values because the field strings aren't being returned by the iterator function.

Example usage: https://gist.github.com/umpc/fc8ab4346eb224aa62005926cff3dd1f

I haven't done any testing other than just getting it working as of yet, but it seems to import all 1,025,920 example features each time. I will push an update and revise the URLs in this comment if I do find a bug.

**Comment by tidwall** [comment] 2018-04-24 01:32
I’m closing this issue because it has been inactive for many months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please feel free to reopen if needed.

Thank you!

**Closed by tidwall** 2018-04-24 01:32 UTC
Labels: enhancement
