### ISSUE TITLE
Does Set Point Increase the RAM

### ISSUE THREAD

**Issue by abhit011** [tidwall/tile38#418] opened 2019-02-25 14:43 UTC
I have been constantly ingesting Set Points close to 10K/sec . Need to know does Set point keeps the trail of all the points in RAM or it just over writes a Set Point for an ID
e.g 
```
	redis.NewStringCmd("set", "fleetX", locData.iD,
						"field", "eventTime", locData.evnDtime,
						"point", locData.laT, locData.loN)
```
Does there will be a single entry of a locData.iD or it will keep trail of all the points that i injest in fleetX against an ID ?

**Comment by rshura** [comment] 2019-02-25 18:30
No history is kept by the `set` command in RAM.  It just updates the object in RAM or creates a new one if it did not yet exist.

**Comment by abhit011** [comment] 2019-03-01 07:19
Lets say there exist close to 100k unique IDs and each object has 
_locData.iD, // 8 bytes
locData.eventTime // 8 bytes
locData.laT, locData.loN // 8 + 8 bytes 
total 24 bytes_ 
In-case if it gets stored as JSON , the size will go little bit more than 24 bytes. Lets consider each object is around 56 bytes.
For 100K it will be 5.6 MB . But in my case it shoots up like crazy. 
There has been 80K hooks, and the total size of those hooks are close to 240 MB . But even in that the RAM for each tile38 instance was close to 540 MB without doing SET POINT and when i started setting the data points , it went to 900 MB, which is insanely large.

**Comment by abhit011** [comment] 2019-03-01 07:21
Is there any way we can get the RSS

**Comment by tidwall** [comment] 2019-03-02 18:05
The [SERVER](https://tile38.com/commands/server) provides details about Tile38's memory usage.
The `mem_alloc` field is the number of bytes that Tile38 is actively using.

**Comment by abhit011** [comment] 2019-03-03 16:46
server gives the allocated by tile38, i am asking about resident set size for the process...

**Comment by tidwall** [comment] 2019-03-03 18:51
Depends on your OS, but for Linux try `ps -u --pid <tile38_pid>`.  Look for the RSS field.

**Comment by abhit011** [comment] 2019-03-04 07:17
the memory fragmentation thats rss/allocated by process is coming = 2.0 
"mem_alloc":230387616, where as the RAM was 620 MB

**Comment by abhit011** [comment] 2019-03-04 10:00
Server command 
_{"ok":true,"stats":{"aof_size":0,"avg_item_size":18095,"cpus":32,"heap_released"
:125075456,"heap_size":203303728,"http_transport":true,"id":"b22f76eb294dd5f3d62
b4ecaa0c8406f","in_memory_size":617925,"max_heap_size":0,"mem_alloc":203303728,"
num_collections":1,"num_hooks":51448,"num_objects":11235,"num_points":11235,"num
_strings":0,"pid":7800,"pointer_size":8,"read_only":false,"threads":58,"version"
:"1.15.0"},"elapsed":"0s"}_
the size of each object is precisely 56 bytes, and there are 11235 objects in one instance but RAM Shoots up to 850 MB with in few seconds, now I am afraid if i leave like this , it might eat up all

**Comment by tidwall** [comment] 2019-03-04 14:17
You should be fine. 

The difference in memory that you are seeing between the RSS and "mem_allos" is because Tile38, which built on the Go runtime, can hang onto idle memory for a long period of time. Basically, it's holding onto memory to avoid having to continually release and reacquire spans of memory from the OS. 

This memory will be eventually released back to the OS, usually in a reasonable amount of time, or when the kernel under pressure.

**Comment by abhit011** [comment] 2019-03-04 14:38
@tidwall 
I agree with you, but there should be some math or upper bound where it should stop , isn't ? Other wise effort has been made to make sure that it does not cross the RAM threshold

**Comment by tidwall** [comment] 2019-03-04 15:52
There's a lot of writeups about how Go memory manager works. This one talks a bit about RSS and spans: https://povilasv.me/go-memory-management/

---

The Tile38/Go memory manager will only acquire a new span of memory from the OS when there isn't a span available to fit the needed local allocation. When you see a discrepancy between RSS and mem_alloc, it's likely because there was a sudden spike in allocations, or possibly there's a high, steady flow of allocations.

In your case, you are pumping in points at 10k/sec. Each SET command must perform a number of operations that require various allocations. Such as reading from the network, parsing the request (possibly geojson), inserting into btree and rtree data structures, and responding to the client.

If you are using webhooks, then there's even more work that needs to be done, including querying for the hooks, generating, queuing, and firing off the notifications.

Each of these allocations may or may not need a new span of memory from the OS. When Tile38 already has space available, then it's likely that that space will be reused.

After these allocations are freed, the Tile38/Go will not necessarily release the spans back to the OS, at least not immediately.

I would be concerned if there's a memory leak in Tile38 and/or if you are seeing the processes being stopped by the oom killer.

**Comment by abhit011** [comment] 2019-03-04 17:44
Thanks for the explanation, I will see the RAM consumption for some hours and then will see what could be done on the same. 
Does the queue.db gets flushed too ? I see it logs the hooks fired and saved into the queue.db but I could see there are few at the beginning of the queue.db file and its not been cleared 
```
hook:log:00000000000000077016
$306
{"command":"set","group":"5c7d5d324696606f1a2efaba","detect":"enter","hook":"geoId_37803#1","key":"fleet","time":"2019-03-04T17:15:30.274993402Z","id":"612143242423","object":{"type":"Point","coordinates":[81.63627555555556,21.317157777777776]},"fields":{"lastIme":1551701915,"Time":1551719728}}
```

**Comment by tidwall** [comment] 2019-03-04 17:47
While on the topic or memory. It may interest you to try the `collection_optz` branch. I added a lot of various memory related optimizations including fewer allocations. In some cases, you'll see as much as a 50% reduction in memory usage.

Since you use the object fields you can also try the `--packed-fields` start-up flag:

```
tile38-server --packed-fields yes
```

Which could dramatically reduce memory usage. This won't totally resolve the RSS vs mem_alloc situation, but it may alleviate some of the stress.

Also, the branch contains `pprof` tooling for analyzing memory in real-time.

Start the server with the -pprofport flag:

```
tile38-server -pprofport 6060
```
Then, at any point, from a different terminal execute:

```
go tool pprof -svg http://localhost:6060/debug/pprof/heap > out.svg
```
Load the SVG into a web browser to visualize the memory usage.

**Comment by tidwall** [comment] 2019-03-04 17:50
The queue.db manages its own bookkeeping. Which includes keeping the file compacted and releasing old entries from memory. The database used for the queue is [BuntDB](https://github.com/tidwall/buntdb).

**Comment by abhit011** [comment] 2019-03-07 09:11
@tidwall 
Is there also some thing on the CPU utilization too in tile38 go server? The hooks are created and they are fixed , they get edited once in a bluemoon, not even every hour not even every day also set points traffic is more or less constant too. But over the time it starts with 0.4% CPU and with in an hour shoots up to 5% ? Does there also exist some science in CPU too ? 

```
{"ok":true,"info":{"aof_current_rewrite_time_sec":0,"aof_enabled":0,"aof_last_re
write_time_sec":0,"aof_rewrite_in_progress":0,"cluster_enabled":0,"connected_cli
ents":2,"connected_slaves":0,"expired_keys":0,"redis_version":"1.16.1","role":"m
aster","tile38_version":"1.16.1","total_commands_processed":1023102,"total_conne
ctions_received":3,"uptime_in_seconds":5684,"used_cpu_sys":92,"used_cpu_sys_chil
dren":0,"used_cpu_user":194,"used_cpu_user_children":0,"used_memory":318663912},
"elapsed":"507.547µs"}
```

**Comment by abhit011** [comment] 2019-03-07 10:09
![image](https://user-images.githubusercontent.com/10906885/53949016-2d20da80-40ef-11e9-8b99-09828948278a.png)

and its keep on increasing

**Comment by abhit011** [comment] 2019-03-07 11:00
![image](https://user-images.githubusercontent.com/10906885/53952252-4f6a2680-40f6-11e9-8cc0-887400a70b4e.png)

**Comment by abhit011** [comment] 2019-03-07 13:47
![image](https://user-images.githubusercontent.com/10906885/53960999-9e6f8600-410d-11e9-9d47-2fc3c2af32bc.png)


```
{"ok":true,"info":{"aof_current_rewrite_time_sec":0,"aof_enabled":0,"aof_last_re
write_time_sec":0,"aof_rewrite_in_progress":0,"cluster_enabled":0,"connected_cli
ents":2,"connected_slaves":0,"expired_keys":0,"redis_version":"1.16.1","role":"m
aster","tile38_version":"1.16.1","total_commands_processed":4676237,"total_conne
ctions_received":4,"uptime_in_seconds":20694,"used_cpu_sys":383,"used_cpu_sys_ch
ildren":0,"used_cpu_user":848,"used_cpu_user_children":0,"used_memory":301272624
},"elapsed":"349.143µs"}
```

**Comment by tidwall** [comment] 2019-03-07 14:11
I'm not aware of any issues relating to the CPU running out of control. It looks like your processing about 12K commands per second. Do you think that 5-6% CPU is too much for your workload?

**Comment by abhit011** [comment] 2019-03-07 14:16
@tidwall , right now the commands that a single instance is accessing is 250 SET POINTS per second . And it is gradually increasing over the time thats what my concern is ? I told the Hooks are same, the Set Point Traffic is constant then why over the time its keep on increasing . We can experience at the beginning of the startup of tile38 server that it will shoot up because it has to do geofence notification for each and every point that first time fed to tile38 server, but after getting stable out it should not grow , it should stay constant .

**Comment by tidwall** [comment] 2019-03-07 14:47
In your case, does the CPU eventually stable out?

**Comment by abhit011** [comment] 2019-03-08 03:56
It was not stable, the only thing i can say that after some time the tile38 instances crashed ... What all logging you expect to troubleshoot this issue

**Comment by tidwall** [comment] 2019-03-08 03:58
Please provide any logs that you may have. Thanks.

**Comment by abhit011** [comment] 2019-03-08 04:04
I have not enabled logs, i will try to reproduce the issue with -vv option , anything else needs

**Comment by abhit011** [comment] 2019-03-12 13:53
`2019/03/12 12:20:23 [WARN] signal: hangup `
But I have ran the command with `nohup<command> > /dir/fileout.out &` 
strange this has occurred only a few times :(

**Comment by tidwall** [comment] 2019-03-12 15:44
Yikes. Tile38 should not be exiting on SIGHUP signals. Thanks for letting me know. 
I fixed the problem in PR #432

**Comment by tidwall** [comment] 2019-03-19 19:15
@abhit011 Are you still getting "signal: hangup" terminations?

**Comment by tidwall** [comment] 2019-03-19 20:53
I just rolled back the SIGHUP #432 change. Please use the `--nohup` flag or the `nohup` command to ignore SIGHUP.

**Comment by abhit011** [comment] 2019-03-20 05:57
@tidwall 
I did not try PR #432 , But I started tile38 instances around 9 days ago, after that i did not see the reset.. But when next time I am starting version tile 38 version 1.16 i will start with --nohup option

**Comment by abhit011** [comment] 2019-04-11 07:53
@tidwall , i feel after continuous usage of tile38, there is increase in CPU continuously week over week .. It can be reproduced easily <Like one week it will be 6% next week it will be 7 and then subsequent week it will be 8 and go on>
Steps
1. Load good number of hooks like close to 100K min.
2. Keep on doing the set point continuously with constant load like close to 1k or 2k per second 

It can be easily produced 

Abhi
:wq

**Comment by tidwall** [comment] 2019-04-12 03:40
@abhit011 I want to reproduce. Is there anything special about the hooks or the point(s)? Such as such location or patterns? Or can any random hook and point work?

**Comment by abhit011** [comment] 2019-04-12 15:41
@tidwall , if you want I will send you the geo fences please share your email id. I will do it. The geofences are either Square or Rectangle. But there might be intersection of multiple sites like this. 
e.g 
![image](https://user-images.githubusercontent.com/10906885/56049345-e1ed8d80-5d66-11e9-8298-36dfab35b6d4.png)
Points movement are like continuous movements of 50k vehicles on a road. And at every second there would be close to 2k set points would be written to tile38 .. I feel if someone has similar case, he/she would had experienced the similar CPU increase case too

Abhi
:wq

**Comment by tidwall** [comment] 2019-04-12 15:46
Providing me with the `SETHOOK` commands and examples of the `SET` commands would be very helpful in reproducing. My email is joshbaker77@gmail.com.

**Comment by tidwall** [comment] 2019-04-13 13:16
I received your geofences in my personal inbox. Thanks for sending them, but I notice that they are just the raw geojson and not in the SETHOOK format. Would it be possible to provide the exact commands that you send to Tile38? 

Ideally, you could provide me with an exact recipe to reproduce the problem.

In addition:

What kind of hardware (OS, memory) is Tile38 running on? 
Are there anything other services running on the server, eg. Docker containers, web middleware, etc?
Please send over samples of the CPU and Memory usage over time? Screenshots of the graphs may be enough.

**Comment by abhit011** [comment] 2019-04-15 07:32
`r1.execute_command('SETHOOK', savetile, 
		    'redis://x.x.x.x:xxxx/fence',
		    'INTERSECTS',
		     'fleet',
		     'FENCE',
		     'DETECT',
		     'enter,exit',
		      'COMMANDS',
		      'set',
		      'OBJECT',
		      hookline)`

**Comment by abhit011** [comment] 2019-04-15 15:05
![image](https://user-images.githubusercontent.com/10906885/56143284-dea00f00-5fbd-11e9-8e58-5436850ab462.png)
3 instances of tile38 running and by evening one of the instance from 6.9 % has gone to 7 Percentage. 
4 Days ago when i did the restart it was at 5% and with in 4 days it touched 7% . I will share more screen grabs in coming days 

Abhi

**Comment by abhit011** [comment] 2019-04-18 05:23
![image](https://user-images.githubusercontent.com/10906885/56338559-21cdce00-61c8-11e9-8cb0-8226dc7e1926.png)

18th April 2019, dump

**Comment by abhit011** [comment] 2019-04-18 14:25
Some how some one in my team did the restart of that linux server and I am sending you its CPU usage when tile 38 it starts ... 
![image](https://user-images.githubusercontent.com/10906885/56367871-df31e300-6213-11e9-84e4-44d071a7192a.png)

**Comment by abhit011** [comment] 2019-04-29 14:36
![image](https://user-images.githubusercontent.com/10906885/56903627-483e1400-6aba-11e9-88c3-76ef6b6d12b1.png)

**Comment by tidwall** [comment] 2019-04-30 17:19
I haven't been able to reproduce the runaway CPU or runaway RAM problems that you describe.  That's not to say it does not exist, it's just that without a reproducible test, crash/panic report, etc. it's been difficult for me to determine the root cause. 

I was hoping, since you first opened this issue, that more technical details would emerge, or perhaps another user would chime in with similar results. This would help to confirm the problem from two or more sources and start a more constructive dialog.

One concern of mine is that this thread has become long and messy. The thread contents no longer represent the title, and the comments are a bit scattered. This might make it hard for someone to jump in and contribute. 

Another concern is the challenge of the problem itself. Since it hasn't been reproduced and there's no clear indication of a root cause, there's little incentive to dig further, thus making the time commitment undefined, and the problem itself a black hole.

I'm closing this issue and I recommend that you reopen a new one with a clear title and a single comment that succinctly describes the problem, and if possible provide crash reports, console logs, etc.

This would hopefully invite others to lend a helping hand.

**Closed by tidwall** 2019-04-30 17:19 UTC
