### ISSUE TITLE
Using requirepass creates strange query results 

### ISSUE THREAD

**Issue by LeonardoBonacci** [tidwall/tile38#564] opened 2020-06-04 09:05 UTC
I secure Tile38 by setting _CONFIG SET requirepass mypass_ from a cli.
When I continue using the same cli everything works well. _CONFIG REWRITE_ persists the password to tile38/data/config. So far so good.

My commands in the first cli are captured in this screenshot: 
![first cli](https://user-images.githubusercontent.com/23434775/83736032-352a4a00-a6a5-11ea-8d69-a43ddb4c0134.png)

When I now close the cli and open another one the interaction is a bit odd.
Second cli commands are captured here: 
![second cli](https://user-images.githubusercontent.com/23434775/83736045-3bb8c180-a6a5-11ea-8bbf-70d748965257.png)

Before authenticating, no results appear and no error message is shown.  
The command _CONFIG GET requirepass_ returns a strangely formatted result.
I've had more of these unformatted results. Either the server returns differently formatted results, or the newly opened cli does not seem capable of printing Json (what would be rather strange).

**Logs**
The server does not log anything. Is there perhaps a way to run the server in debugging mode?

**Operating System (please complete the following information):**
 - OS: Windows 10, and also in docker image: latest Tile38 version 1.20.0

Looks like what's explained [here](https://redis.io/topics/protocol) perhaps?

**Comment by tidwall** [comment] 2020-06-04 19:58
Thanks for reporting this issue. I found the cause and just pushed a fix.

**Closed** 2020-06-04 19:57 UTC

**Comment by LeonardoBonacci** [comment] 2020-06-05 08:23
Thanks for the quick fix!
I've added an [authentication property](https://github.com/LeonardoBonacci/kafka-connect-tile38-sink/commit/0359122308f2b8c2ddaaf9540a6139a7058110d4) to an almost official Confluent Kafka Tile38 Sink Connector.

Keep you informed!

**Comment by tidwall** [comment] 2020-06-05 21:22
You're welcome.

I look forward to seeing your Tile38 sink connector go live!

**Comment by LeonardoBonacci** [comment] 2020-06-05 23:04
They're very quick at Confluent too. Here it is: https://www.confluent.io/hub/leonardobonacci/kafka-connect-tile38-sink
